# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import graph_pb2 as graph__pb2


class GraphServiceStub(object):
    """Interface definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/nebula.proto.graph.GraphService/Authenticate',
                request_serializer=graph__pb2.AuthRequest.SerializeToString,
                response_deserializer=graph__pb2.AuthResponse.FromString,
                )
        self.Execute = channel.unary_unary(
                '/nebula.proto.graph.GraphService/Execute',
                request_serializer=graph__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=graph__pb2.ExecuteResponse.FromString,
                )
        self.StreamingExecute = channel.unary_stream(
                '/nebula.proto.graph.GraphService/StreamingExecute',
                request_serializer=graph__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=graph__pb2.ExecuteResponse.FromString,
                )


class GraphServiceServicer(object):
    """Interface definition
    """

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingExecute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=graph__pb2.AuthRequest.FromString,
                    response_serializer=graph__pb2.AuthResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=graph__pb2.ExecuteRequest.FromString,
                    response_serializer=graph__pb2.ExecuteResponse.SerializeToString,
            ),
            'StreamingExecute': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamingExecute,
                    request_deserializer=graph__pb2.ExecuteRequest.FromString,
                    response_serializer=graph__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nebula.proto.graph.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GraphService(object):
    """Interface definition
    """

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nebula.proto.graph.GraphService/Authenticate',
            graph__pb2.AuthRequest.SerializeToString,
            graph__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nebula.proto.graph.GraphService/Execute',
            graph__pb2.ExecuteRequest.SerializeToString,
            graph__pb2.ExecuteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nebula.proto.graph.GraphService/StreamingExecute',
            graph__pb2.ExecuteRequest.SerializeToString,
            graph__pb2.ExecuteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
