#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
#

from __future__ import absolute_import
import six
from nebula.fbthrift.util.Recursive import fix_spec
from nebula.fbthrift.Thrift import *
from nebula.fbthrift.protocol.TProtocol import TProtocolException



from .ttypes import *

kInvalidValueType = ValueType(**{
  "type" :   0,
})

