DEFAULT_CONNECT_TIMEOUT = 3  # 3 seconds
DEFAULT_REQUEST_TIMEOUT = 60  # 1 minute

DEFAULT_MAX_CLIENT_SIZE = 10
DEFAULT_MIN_CLIENT_SIZE = 1
DEFAULT_TEST_ON_BORROW = False
DEFAULT_STRICTLY_SERVER_HEALTHY = False
DEFAULT_MAX_WAIT = 60  # 1 minute

DEFAULT_SESSION_POOL_SIZE = 4
DEFAULT_SESSION_POOL_WAIT_TIMEOUT = 60  # 1 minute
DEFAULT_SESSION_POOL_WAIT_RETRY_INTERVAL = 0.1
